### ISSUE TITLE
Data footnotes

### ISSUE THREAD

**Issue by maxwellkrieger** [pph-collective/signal-app#125]
- Add a new div/card section that contains footnotes around data points
- Clarify data processing, analysis, and interpretation notes
- Include limitations of data and analyses
- Include links out to documentation of processes if available

**Comment by williamgoedel** [comment]
**DRAFT TEXT**

This web tool includes information on vaccines administered to Rhode Island residents as recorded in the [Rhode Island Child and Adult Immunization Registry](https://health.ri.gov/programs/detail.php?pgm_id=156681) at the Rhode Island Department of Health. Rhode Island residents with invalid or incomplete residential address information are excluded. Data for Rhode Island residents who were vaccinated at federal facilities or in other states are not included unless they have submitted a copy of their vaccination record to the Rhode Island Department of Health. 

Estimates of population size are sourced from the United States Census Bureau's [American Community Survey](https://www.census.gov/programs-surveys/acs) (2015-2019, 5-year estimates). There is statistical uncertainty associated with these estimates, particularly for small populations in small geographic areas, resulting in estimates of vaccine coverage that are unreliable. Some estimates may be suppressed in line with the Rhode Island Department of Health's [Small Numbers Reporting Policy](https://health.ri.gov/publications/policies/SmallNumbersReporting.pdf). All vaccine coverage estimates are capped at 99%.
