### ISSUE TITLE
Test on iPad

### ISSUE THREAD

**Issue by eldu** [pph-collective/signal-app#168]

**Comment by maxwellkrieger** [comment]
Just did some snooping around on an iPad. Initial findings:

- Overall, things look good on both portrait & landscape mode. Text sizing is sufficient.
- The map on _non zoomed_ mode (default setting) is not touch-scrollable. Meaning you cannot touch the area inside the map to scroll up or down the page. Once zooming to a neighborhood, you can touch the map area to scroll the page up and down
- Tooltips for our little red dots linger even after scrolling outside of the map area. The map area has to be selected again for the tooltip to disappear. The same thing happens with the gap chart tooltips.

**Comment by eldu** [comment]
Created #188 #187
