### ISSUE TITLE
Zoom to HEZ

### ISSUE THREAD

**Issue by s-bessey** [pph-collective/signal-app#180]
Along with zooming to municipality, the tool should be able to zoom to a give Health Equity Zone (HEZ)

**Comment by maxwellkrieger** [comment]
[HEZ_Boundaries.zip](https://github.com/pph-collective/signal-app/files/10189790/HEZ_Boundaries.zip)

Sticking this here just as a reminder to ourselves that Will has provided the spatial files necessary

**Comment by maxwellkrieger** [comment]
We will include these locations on the top of the list for the muni dropdown (similar to how we do it for PROVIDENT)
