### ISSUE TITLE
Update GapChart to work with lower booster coverage

### ISSUE THREAD

**Issue by s-bessey** [pph-collective/signal-app#200]
The booster coverage is now super low, leading to the GapChart no longer showing the full "x% vaccinated" 
![image](https://user-images.githubusercontent.com/45404173/231802974-3ba20c8b-9732-49ac-a509-94ddfb8feac6.png)

**Comment by eldu** [comment]
Adjust the domain based on the state % vaccinated. Hopefully the data will not cut off the text.

Sketch up some other ideas as you familiarize with vega ! ❤️
