### ISSUE TITLE
Add analytics events

### ISSUE THREAD

**Issue by mcmcgrath13** [pph-collective/signal-app#38]
What (if any) specific user interactions to we want to record to google analytics?

**Comment by maxwellkrieger** [comment]
Are we tracking any events currently @eldu ? Even just pageviews

**Comment by eldu** [comment]
@maxwellkrieger

Hmm, I don't think we do? I didn't see any google analytics in the code. There is some analytics on firebase?
https://console.firebase.google.com/u/1/project/profoundmodel/firestore/usage/last-24h/reads
